import { useState, type FormEvent } from "react";
import { useAuth } from "../auth/AuthProvider";
import { ApiError } from "../api/client";
import { useRouter } from "../routes/router";

export function AuthScreen({mode}:{mode:"login"|"register"}) {
  const {login,register}=useAuth(); const {navigate}=useRouter(); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);try{if(mode==="register")await register(String(form.get("name")),String(form.get("email")),String(form.get("password")),String(form.get("invitation_code")||""),form.get("terms")==="on");else await login(String(form.get("email")),String(form.get("password")));navigate(mode==="register"?"/onboarding":"/app/dashboard",true)}catch(error){setMessage(error instanceof ApiError?(mode==="register"?error.message:"We could not sign you in. Check your details and try again."):mode==="register"?"We could not create your account. Please try again.":"We could not sign you in. Check your details and try again.")}finally{setBusy(false)}}
  return <main className="auth"><section><p className="eyebrow">Speak with confidence</p><h1>Your English,<br/>your pace,<br/><em>your tutor.</em></h1><p>Natural Indian-English practice with an animated 2D tutor.</p></section><form className="card" onSubmit={submit} aria-describedby={message?"auth-error":undefined}><h2>{mode==="register"?"Start practising":"Continue learning"}</h2>{mode==="register"&&<><label>Name<input name="name" required maxLength={100} autoComplete="name"/></label><label>Closed-beta invitation code (if provided)<input name="invitation_code" maxLength={100} autoComplete="off"/></label></>}<label>Email<input name="email" type="email" required autoComplete="email"/></label><label>Password<input name="password" type="password" minLength={12} required autoComplete={mode==="login"?"current-password":"new-password"}/></label>{mode==="login"&&<button type="button" className="link" onClick={()=>navigate("/forgot-password")}>Forgot password?</button>}{mode==="register"&&<label><input name="terms" type="checkbox" required/> I accept the Terms and Privacy Policy drafts for this closed beta.</label>}<button disabled={busy}>{busy?"Please wait…":mode==="register"?"Create learner account":"Login"}</button><button type="button" className="link" onClick={()=>navigate(mode==="login"?"/register":"/login")}>{mode==="login"?"Create a new account":"I already have an account"}</button><p className="legal-links"><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/refunds">Refunds</a><a href="/support">Support</a></p><p id="auth-error" role="alert" aria-live="assertive" className="message">{message}</p></form></main>
}
