import { useEffect, useState, type FormEvent } from "react";
import { api } from "../api/client";
import type { ProgressDetail, SubscriptionView } from "../models";

export function FeedbackScreen(){const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const file=form.get("screenshot");try{const result=await api.feedback({rating:Number(form.get("rating")),category:String(form.get("category")),severity:String(form.get("severity")),message:String(form.get("message")),contact_allowed:form.get("contact_allowed")==="on",screenshot_name:file instanceof File&&file.name?file.name:undefined});setMessage(result.message);event.currentTarget.reset()}catch(error){setMessage(error instanceof Error?error.message:"Feedback could not be submitted.")}finally{setBusy(false)}}return <section className="page narrow"><h1>Tell us what happened.</h1><p>Closed-beta feedback goes to the product team. A screenshot is optional; only its safe filename is recorded in this release candidate.</p><form className="card form-grid" onSubmit={submit}><label>Rating<select name="rating" defaultValue="5">{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select name="category"><option value="lesson">Lesson</option><option value="onboarding">Onboarding</option><option value="voice">Voice</option><option value="subscription">Subscription</option><option value="support">Support</option><option value="other">Other</option></select></label><label>Severity<select name="severity"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>BLOCKING</option></select></label><label className="wide">What happened?<textarea name="message" required minLength={3} maxLength={1000}/></label><label className="wide">Optional screenshot<input name="screenshot" type="file" accept="image/png,image/jpeg,image/webp"/></label><label className="wide"><input name="contact_allowed" type="checkbox"/> You may contact me about this feedback.</label><button disabled={busy}>{busy?"Sending…":"Send feedback"}</button><p role="status">{message}</p></form></section>}

function subscriptionDate(value:string|null){return value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value)):"Not applicable"}

export function SubscriptionScreen(){
  const[data,setData]=useState<SubscriptionView>();const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);
  const load=async()=>{setLoading(true);setMessage("");try{setData(await api.subscription())}catch{setData(undefined);setMessage("Your subscription details are temporarily unavailable. Please retry.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  async function trial(){if(busy)return;setBusy(true);try{await api.startTrial();setMessage("Your test-mode trial started. No payment was charged.");await load()}catch{setMessage("The trial could not be started. Please retry.")}finally{setBusy(false)}}
  async function upgrade(){if(busy)return;setBusy(true);try{const result=await api.requestUpgrade();setMessage(result.real_charge?"Payments are unavailable. No action was taken.":"Premium preview opened in test mode. No subscription or charge was created.")}catch{setMessage("The premium preview is temporarily unavailable. Please retry.")}finally{setBusy(false)}}
  return <section className="page subscription-page"><header className="subscription-heading"><div><p className="eyebrow">Membership</p><h1>Your plan, clearly explained.</h1><p>See what you have today and compare closed-beta options without surprise charges.</p></div><p className="test-banner">Payment preview only<br/><small>No real payment will be collected.</small></p></header>
    {loading&&<p aria-live="polite">Loading your plan…</p>}
    {!loading&&!data&&<section className="card subscription-error"><p role="alert">{message}</p><button onClick={()=>void load()}>Retry subscription details</button></section>}
    {data&&<>
      <section className="current-plan" aria-label="Current subscription"><div><p>Current plan</p><h2>{data.plan_name}</h2><strong className={`status-pill status-${data.status.toLowerCase()}`}>{data.status.replaceAll("_"," ")}</strong></div><dl><div><dt>Started</dt><dd>{subscriptionDate(data.started_at)}</dd></div><div><dt>{data.status==="TRIAL"?"Trial ends":"Renews or expires"}</dt><dd>{subscriptionDate(data.current_period_end)}</dd></div><div><dt>Daily tutor allowance</dt><dd>{data.entitlements.daily_conversations} conversations</dd></div><div><dt>Daily voice allowance</dt><dd>{data.entitlements.voice_minutes} minutes</dd></div></dl>{data.status==="TRIAL"&&<p><strong>{data.trial_remaining_days} trial days remaining.</strong></p>}<ul>{data.active_features.map(feature=><li key={feature}>{feature}</li>)}</ul></section>
      <section aria-labelledby="available-plans"><h2 id="available-plans">Available plans</h2><div className="subscription-plans">{data.available_plans.map(plan=><article className={plan.code===data.plan_id?"plan-card current":"plan-card"} key={plan.code}><p>{plan.code===data.plan_id?"Your current plan":"Available in closed beta"}</p><h3>{plan.name}</h3><strong className="plan-price">{plan.price_inr===0?"Free":`₹${plan.price_inr.toLocaleString("en-IN")}`} <small>{plan.billing_period}</small></strong><ul>{plan.features.map(feature=><li key={feature}>{feature}</li>)}</ul>{plan.code==="PREMIUM_MONTHLY"&&data.can_start_trial&&<button disabled={busy} onClick={()=>void trial()}>Start 7-day test trial</button>}{plan.code!=="FREE"&&<button className="secondary-action" disabled={busy||!data.can_preview_upgrade} onClick={()=>void upgrade()}>Preview {plan.name}</button>}</article>)}</div></section>
      <aside className="payment-safety"><strong>Before you continue</strong><p>{data.payment_notice}</p><p>{data.fair_use}</p></aside>
    </>}
    {data&&<p role="status" aria-live="polite">{message}</p>}
  </section>
}

export function ProgressDetailScreen(){const[data,setData]=useState<ProgressDetail>();const[error,setError]=useState("");useEffect(()=>{api.progressDetail().then(setData).catch(e=>setError(e instanceof Error?e.message:"Progress could not be loaded."))},[]);if(error)return <p role="alert">{error}</p>;if(!data)return <p>Loading progress…</p>;return <section className="page"><h1>Small practice. Real momentum.</h1><div className="progress-grid">{Object.entries(data.scores).map(([label,value])=><article key={label}><strong>{value??"—"}</strong><span>{label}{value===null?" · not measured yet":" · average score"}</span></article>)}</div><div className="dashboard-grid secondary"><article className="metric"><strong>{data.completed_lessons}</strong><span>completed lessons</span></article><article className="metric"><strong>{data.daily_streak}</strong><span>Current streak</span></article><article className="metric"><strong>{data.weekly_activity}</strong><span>activities this week</span></article><article className="metric"><strong>{data.monthly_activity}</strong><span>activities this month</span></article></div><article className="card"><h2>Learning goal</h2><p>{data.learning_goal||"Choose a learning goal during onboarding."}</p><h2>Conversation history</h2><p>{data.conversation_history_summary.conversations} conversations · {data.conversation_history_summary.recent_sessions} recent sessions</p><h2>Recent achievements</h2><p>{data.recent_achievements.length?data.recent_achievements.join(" · "):"Achievements will appear after verified practice milestones."}</p></article></section>}

export function FounderScreen(){const[data,setData]=useState<Record<string,unknown>>();const[error,setError]=useState("");useEffect(()=>{api.founderDashboard().then(setData).catch(e=>setError(e instanceof Error?e.message:"Dashboard unavailable."))},[]);if(error)return <section className="page"><h1>Founder dashboard</h1><p role="alert">{error}</p></section>;if(!data)return <p>Loading founder dashboard…</p>;const metrics=["users","daily_registrations","active_users","trials","paid_users","estimated_mrr_inr","estimated_arr_inr","openai_usage","estimated_ai_cost_usd","average_ai_cost_usd","feedback_count","health","system_status"];return <section className="page"><h1>Founder dashboard</h1><p className="test-banner">Read-only release-candidate operations view.</p><div className="progress-grid">{metrics.map(key=><article key={key}><strong>{String(data[key]??"—")}</strong><span>{key.replaceAll("_"," ")}</span></article>)}</div><article className="card"><h2>Subscription overview</h2><pre>{JSON.stringify(data.subscription_overview,null,2)}</pre><h2>Recent registrations</h2><pre>{JSON.stringify(data.recent_registrations,null,2)}</pre><h2>Recent feedback</h2><pre>{JSON.stringify(data.recent_feedback,null,2)}</pre></article></section>}
