import { useState, type FormEvent } from "react";
import { ApiError, api } from "../api/client";
import { useRouter } from "../routes/router";

export function RequestPasswordResetScreen() {
  const {navigate}=useRouter(); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const email=String(new FormData(event.currentTarget).get("email"));try{const result=await api.requestPasswordReset(email);sessionStorage.setItem("speakmate.reset.email",email);setMessage(result.message);navigate("/reset-password");}catch{setMessage("We could not process the request. Please wait and try again.");}finally{setBusy(false)}}
  return <main className="auth"><section><p className="eyebrow">Account recovery</p><h1>Reset your<br/><em>password.</em></h1><p>We will email a six-digit, single-use verification code.</p></section><form className="card" onSubmit={submit}><h2>Forgot password</h2><label>Email<input name="email" type="email" required autoComplete="email"/></label><button disabled={busy}>{busy?"Please wait…":"Send verification code"}</button><button type="button" className="link" onClick={()=>navigate("/login")}>Back to login</button><p role="status" aria-live="polite" className="message">{message}</p></form></main>;
}

export function UpdatePasswordScreen() {
  const {navigate}=useRouter(); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [complete,setComplete]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const email=String(form.get("email"));const code=String(form.get("code"));const password=String(form.get("password"));try{await api.validatePasswordReset(email,code);setMessage((await api.confirmPasswordReset(email,code,password)).message);sessionStorage.removeItem("speakmate.reset.email");setComplete(true);}catch(error){setMessage(error instanceof ApiError?error.message:"We could not update your password.");}finally{setBusy(false)}}
  return <main className="auth"><section><p className="eyebrow">Account recovery</p><h1>Choose a new<br/><em>password.</em></h1><p>Enter the code from your email. Your existing signed-in sessions will be revoked.</p></section><section className="card"><h2>Update password</h2>{!complete&&<form onSubmit={submit}><label>Email<input name="email" type="email" required autoComplete="email" defaultValue={sessionStorage.getItem("speakmate.reset.email")||""}/></label><label>Six-digit verification code<input name="code" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required autoComplete="one-time-code"/></label><label>New password<input name="password" type="password" minLength={12} maxLength={72} required autoComplete="new-password"/></label><button disabled={busy}>{busy?"Please wait…":"Update password"}</button></form>}<p role="status" aria-live="polite" className="message">{message}</p>{complete&&<button type="button" onClick={()=>navigate("/login",true)}>Back to login</button>}</section></main>;
}
