from enum import StrEnum


class ProficiencyLevel(StrEnum):
    STARTER = "STARTER"
    BEGINNER = "BEGINNER"
    ELEMENTARY = "ELEMENTARY"
    PRE_INTERMEDIATE = "PRE_INTERMEDIATE"
    INTERMEDIATE = "INTERMEDIATE"


class LearningGoal(StrEnum):
    DAILY_CONVERSATION = "DAILY_CONVERSATION"
    JOB_INTERVIEW = "JOB_INTERVIEW"
    WORKPLACE = "WORKPLACE"
    TRAVEL = "TRAVEL"
    GENERAL_FLUENCY = "GENERAL_FLUENCY"


class NativeLanguage(StrEnum):
    TELUGU = "Telugu"
    ENGLISH = "English"


class LessonSessionStatus(StrEnum):
    STARTED = "STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"


class AudioAssetStatus(StrEnum):
    TEMPORARY = "TEMPORARY"
    RETAINED = "RETAINED"
    PENDING_DELETION = "PENDING_DELETION"
    DELETED = "DELETED"
