export type TutorGender = "female" | "male";
export interface Tutor { tutor_id:string; display_name:string; gender:TutorGender; avatar_profile:string; voice_profile:string; accent:"Indian English"; teaching_style:string; animation_profile:string; prompt_profile:string; vocabulary_profile:string; enabled:boolean }
export interface TokenPair { access_token:string; refresh_token:string; token_type:"bearer"; expires_in:number }
export interface Account { id:string; learner_id:string; email:string; mobile_number?:string|null; status:string }
export type LanguageMode = "ENGLISH"|"ENGLISH_TELUGU"|"TELUGU_DOMINANT";
export interface TutorPreference { learner_id:string; tutor:Tutor; telugu_explanations_enabled:boolean; language_mode:LanguageMode }
export interface Dashboard { learner_id:string; completed_sessions:number; current_streak_days:number; total_practice_minutes:number; preferred_tutor_id:string; subscription_tier:string; subscription_status:string }
export interface CurriculumLesson { id:string; title:string; category:string; proficiency_level:string; scenario_id:string; learning_objectives:string[]; target_vocabulary:string[]; grammar_focus:string[]; estimated_duration_minutes:number; completion_criteria:string; instruction_prompt:string; practice_prompt:string; roleplay_prompt:string }
export interface LessonSession { id:string; learner_id:string; lesson_id:string; conversation_id?:string|null; status:"STARTED"|"IN_PROGRESS"|"COMPLETED"|"ABANDONED"; started_at:string; completed_at?:string|null; duration_seconds:number }
export interface AiTurn { turn_id:string; tutor_message:string; next_question:string; corrected_sentence?:string|null; incorrect_span?:string|null; corrected_form?:string|null; correction_explanation?:string|null; correction_explanation_default?:string|null; vocabulary_suggestions:string[]; telugu_explanation?:string; language_mode?:LanguageMode; review_changed?:boolean; review_reason_code?:string; preserved_learning_terms?:string[]; expression_hint?:string; language_review_status?:"COMPLETED"|"DEGRADED"; language_review_failure_code?:string|null; spoken_text?:string; coaching_mode?:"NO_CORRECTION"|"LIGHT_CORRECTION"|"RETRY_REQUIRED"; coaching_state?:"NORMAL_CONVERSATION"|"CORRECTION_PRESENTED"|"WAITING_FOR_RETRY"|"RETRY_ACCEPTED"|"CONTINUE_CONVERSATION"|"EXPLAINING_CORRECTION"; retry_of_turn_id?:string|null; learner_intent?:"RETRY"|"EXPLANATION"|"GRAMMAR_HELP"|"CLARIFICATION"|"EXAMPLES"|"LANGUAGE_CHANGE"|"GUIDED_ROLEPLAY"|"NORMAL_CONVERSATION"; explanation_language?:"TELUGU"|"ENGLISH"; explanation_language_state?:"DEFAULT_PREFERENCE"|"ONE_TURN_OVERRIDE"|"PERSISTENT_PREFERENCE_CHANGE" }
export interface TutorSpeech {blob:Blob;provider:string;model:string;voice:string;cacheStatus:string;inputCharacters:number;providerRequests:number;usageClassification:string}
export interface VoiceTranscription { transcript:string; detected_language:string; confidence?:number|null; duration_ms:number; size_bytes:number }
export interface SubscriptionPlan {code:string;name:string;price_inr:number;billing_period:string;features:string[]}
export interface SubscriptionView {plan_id:string;plan_name:string;status:string;trial_remaining_days:number;payment_mode:"test";started_at:string|null;current_period_end:string|null;entitlements:{daily_conversations:number;voice_minutes:number;progress_history:boolean;conversation_history:boolean};active_features:string[];available_plans:SubscriptionPlan[];can_start_trial:boolean;can_preview_upgrade:boolean;payment_notice:string;fair_use:string}
export interface ProgressDetail {scores:Record<"grammar"|"vocabulary"|"pronunciation"|"confidence"|"fluency",number|null>;completed_lessons:number;daily_streak:number;weekly_activity:number;monthly_activity:number;learning_goal:string;recent_achievements:string[];conversation_history_summary:{conversations:number;recent_sessions:number}}
export type AppRoute = "/"|"/pricing"|"/privacy"|"/terms"|"/refunds"|"/support"|"/faq"|"/login"|"/register"|"/forgot-password"|"/reset-password"|"/onboarding"|"/app/dashboard"|"/app/daily-lesson"|"/app/conversation"|"/app/progress"|"/app/settings"|"/app/feedback"|"/app/subscription"|"/app/founder";
