import{expect,test,type Page}from"@playwright/test";
const token={access_token:"access",refresh_token:"refresh-token-value-long-enough",token_type:"bearer",expires_in:900};const account={id:"user-1",learner_id:"learner-1",email:"browser@example.invalid",status:"ACTIVE"};const tutor=(id:"ananya"|"arjun")=>({tutor_id:id,display_name:id==="ananya"?"Ananya":"Arjun",gender:id==="ananya"?"female":"male",avatar_profile:`/tutors/${id}.jpg`,voice_profile:`indian-english-${id}`,accent:"Indian English",teaching_style:"patient and encouraging",animation_profile:"animated-2d",prompt_profile:"supportive",vocabulary_profile:"practical",enabled:true});
async function mockApi(page:Page){await page.route("**/api/v1/**",async route=>{const url=new URL(route.request().url()),path=url.pathname;let body:unknown={};if(path.endsWith("/login"))body=token;else if(path.endsWith("/me"))body=account;else if(path==="/api/v1/tutors")body=[tutor("ananya"),tutor("arjun")];else if(path.endsWith("/preference"))body={learner_id:"learner-1",tutor:tutor("ananya"),telugu_explanations_enabled:true};else if(path.endsWith("/dashboard"))body={learner_id:"learner-1",completed_sessions:3,current_streak_days:2,total_practice_minutes:8,preferred_tutor_id:"ananya",subscription_tier:"FREE",subscription_status:"READY_FOR_PROVIDER_INTEGRATION"};else if(path.endsWith("/conversations"))body={id:"conversation-1"};else if(path.endsWith("/ai-turns"))body={tutor_message:"Thanks for sharing.",next_question:"What happened next?",correction_explanation:"Use the past tense here.",vocabulary_suggestions:["confident","routine"],telugu_explanation:"ఇక్కడ భూతకాలం ఉపయోగించండి."};await route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(body)})})}
async function authenticated(page:Page){await page.addInitScript(value=>sessionStorage.setItem("speakmate.session.v1",JSON.stringify(value)),token);await mockApi(page)}
for(const [name,width]of[["mobile",390],["tablet",768],["desktop",1440]]as const)test(`${name} login viewport`,async({page})=>{await page.setViewportSize({width,height:850});await mockApi(page);await page.goto("/login");await expect(page.getByRole("heading",{name:"Continue learning"})).toBeVisible()});
test("protected redirect and login",async({page})=>{await mockApi(page);await page.goto("/app/dashboard");await expect(page).toHaveURL(/\/login$/);await page.getByLabel("Email").fill("browser@example.invalid");await page.getByLabel("Password").fill("StrongPassword123!");await page.getByRole("button",{name:"Login"}).click();await expect(page.getByText("Ready for today’s conversation?")).toBeVisible()});
test("tutor selection and Settings change",async({page})=>{await authenticated(page);await page.goto("/onboarding");await page.getByRole("radio",{name:/Ananya/}).click();await expect(page.getByRole("radio",{name:/Ananya/})).toHaveAttribute("aria-checked","true");await page.getByRole("radio",{name:/Arjun/}).click();await page.getByRole("button",{name:"Continue with my tutor"}).click();await page.getByRole("button",{name:"Settings"}).click();await page.getByRole("button",{name:"Change tutor"}).click();await expect(page.getByRole("radio",{name:/Arjun/})).toBeVisible()});
test("lesson, conversation feedback, Telugu, reduced motion, and clean console",async({page})=>{const errors:string[]=[];page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});await page.emulateMedia({reducedMotion:"reduce"});await authenticated(page);await page.goto("/app/daily-lesson");await expect(page.getByText("A confident morning routine")).toBeVisible();await page.getByRole("button",{name:"Begin lesson"}).click();await page.getByLabel("Your message").fill("I go yesterday");await page.getByRole("button",{name:"Send"}).click();await expect(page.getByText("Use the past tense here.")).toBeVisible();await expect(page.getByText("confident")).toBeVisible();await expect(page.getByText(/భూతకాలం/)).toBeVisible();await expect(page.locator(".avatar")).toHaveClass(/reduced-motion/);expect(errors).toEqual([])});
test("microphone denial remains recoverable with text",async({page})=>{await authenticated(page);await page.addInitScript(()=>Object.defineProperty(navigator,"mediaDevices",{configurable:true,value:{getUserMedia:()=>Promise.reject(new DOMException("denied","NotAllowedError"))}}));await page.goto("/app/conversation");await page.getByLabel(/consent to voice processing/).check();await page.getByRole("button",{name:"Start microphone"}).click();await expect(page.getByRole("alert")).toContainText("permission was denied");await expect(page.getByLabel("Your message")).toBeEnabled()});
